/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lorraine.main;

import com.formdev.flatlaf.FlatClientProperties;
import com.lorraine.views.AuthPanel;
import com.lorraine.views.TransactionsPanel;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author Lorraine G. Bulaclac, seany
 */
public class MainPanel extends javax.swing.JPanel {
    
    private JButton activeButton = null;
    /**
     * Creates new form MainPanel
     */
    public MainPanel() {
        initComponents();
        contentPanel.setLayout(new BorderLayout());
        initComponentProperties();
        initNavigationButtons();
        initUserCard();
        setActiveButton(transactionsButton);
    }
    
    private void initComponentProperties() {
        navigationPanel.setBackground(new Color(248, 248, 246));
        navigationPanel.setBorder(BorderFactory.createMatteBorder(0, 0, 0, 1, new Color(232, 232, 228)));
        contentPanel.setBackground(Color.WHITE);
        logoPanel.setBorder(BorderFactory.createMatteBorder(0, 0, 1, 0, new Color(232, 232, 228)));
        userCard.setBorder(BorderFactory.createMatteBorder(1, 0, 0, 0, new Color(232, 232, 228)));
    }
    
    private void initNavigationButtons() {
            transactionsButton.addActionListener(e -> setActiveButton(transactionsButton));
            transactionsButton.addMouseListener(new MouseAdapter() {
                @Override public void mouseEntered(MouseEvent e) {
                    if (transactionsButton != activeButton) applyStyle(transactionsButton, "rgb(237,237,234)", "rgb(17,17,17)");
                }
                @Override public void mouseExited(MouseEvent e) {
                    if (transactionsButton != activeButton) applyStyle(transactionsButton, "rgb(248,248,246)", "rgb(17,17,17)");
                }
            });
            applyStyle(transactionsButton, "rgb(248,248,246)", "rgb(17,17,17)");
    }
    
    private void initUserCard() {
        String firstName = Session.getUser().getFirstName();
        String lastName  = Session.getUser().getLastName();

        String initials    = firstName.substring(0, 1).toUpperCase()
                           + lastName.substring(0, 1).toUpperCase();
        String displayName = firstName + " " + lastName.substring(0, 1).toUpperCase() + ".";
        String email       = Session.getUser().getEmail();

        avatarLabel.setText(initials);
        userNameLabel.setText(displayName);
        userEmailLabel.setText(email);
    }

    private void applyStyle(JButton button, String bg, String fg) {
        button.putClientProperty(FlatClientProperties.STYLE,
            "arc:8; borderWidth:0; focusWidth:0; innerFocusWidth:0; "
          + "margin:8,14,8,14; background:" + bg + "; foreground:" + fg);
    }
    
    public void setContentView(JPanel panel) {
        contentPanel.removeAll();
        contentPanel.add(panel, BorderLayout.CENTER);
        contentPanel.revalidate();
        contentPanel.repaint();
    }
    
    private void logout() {
        Session.logout();
        MainFrame mainFrame = (MainFrame) SwingUtilities.getWindowAncestor(this);
        if (mainFrame != null) {
            mainFrame.setView(new AuthPanel());
        }
    }
    
    private void applyLogoutStyle(boolean hovered) {
        String bg = hovered ? "rgb(254,226,226)" : "rgb(248,248,246)";
        logoutButton.putClientProperty(FlatClientProperties.STYLE,
            "arc:8; borderWidth:0; focusWidth:0; innerFocusWidth:0; "
          + "margin:8,14,8,14; background:" + bg + "; foreground:rgb(180,40,40)");
    }
    
    private void setActiveButton(JButton button) {
        if (activeButton != null) applyStyle(activeButton, "rgb(248,248,246)", "rgb(17,17,17)");
        applyStyle(button, "rgb(17,17,17)", "rgb(255,255,255)");
        activeButton = button;
        if (button == transactionsButton) {
            setContentView(new TransactionsPanel());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        navigationPanel = new javax.swing.JPanel();
        logoPanel = new javax.swing.JPanel();
        logoLabel = new javax.swing.JLabel();
        logoSubLabel = new javax.swing.JLabel();
        bottomPanel = new javax.swing.JPanel();
        logoutButton = new javax.swing.JButton();
        userCard = new javax.swing.JPanel();
        avatarPanel = new javax.swing.JPanel();
        avatarLabel = new javax.swing.JLabel();
        userInfoPanel = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        userEmailLabel = new javax.swing.JLabel();
        menuLabel = new javax.swing.JLabel();
        transactionsButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1020, 620));

        navigationPanel.setBackground(new java.awt.Color(248, 248, 246));
        navigationPanel.setPreferredSize(new java.awt.Dimension(200, 620));

        logoPanel.setBackground(new java.awt.Color(248, 248, 246));

        logoLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        logoLabel.setForeground(new java.awt.Color(51, 216, 25));
        logoLabel.setText("PesoTrack");

        logoSubLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        logoSubLabel.setForeground(new java.awt.Color(136, 136, 128));
        logoSubLabel.setText("Personal Finance");

        javax.swing.GroupLayout logoPanelLayout = new javax.swing.GroupLayout(logoPanel);
        logoPanel.setLayout(logoPanelLayout);
        logoPanelLayout.setHorizontalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoSubLabel)
                    .addComponent(logoLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logoPanelLayout.setVerticalGroup(
            logoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(logoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoSubLabel)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        bottomPanel.setBackground(new java.awt.Color(248, 248, 246));
        bottomPanel.setPreferredSize(new java.awt.Dimension(220, 50));

        logoutButton.setBackground(new java.awt.Color(248, 248, 246));
        logoutButton.setForeground(new java.awt.Color(180, 40, 40));
        logoutButton.setText("Sign Out");
        logoutButton.setBorder(null);
        logoutButton.setPreferredSize(new java.awt.Dimension(190, 40));
        logoutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutButtonMouseExited(evt);
            }
        });
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userCard.setBackground(new java.awt.Color(248, 248, 246));
        userCard.setPreferredSize(new java.awt.Dimension(200, 50));

        avatarPanel.setBackground(new java.awt.Color(255, 51, 51));
        avatarPanel.setPreferredSize(new java.awt.Dimension(34, 34));

        avatarLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        avatarLabel.setForeground(new java.awt.Color(255, 255, 255));
        avatarLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avatarLabel.setPreferredSize(new java.awt.Dimension(22, 22));

        javax.swing.GroupLayout avatarPanelLayout = new javax.swing.GroupLayout(avatarPanel);
        avatarPanel.setLayout(avatarPanelLayout);
        avatarPanelLayout.setHorizontalGroup(
            avatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avatarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        avatarPanelLayout.setVerticalGroup(
            avatarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avatarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avatarLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        userInfoPanel.setBackground(new java.awt.Color(248, 248, 246));
        userInfoPanel.setPreferredSize(new java.awt.Dimension(140, 34));

        userNameLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(17, 17, 17));
        userNameLabel.setText("User");
        userNameLabel.setToolTipText("");

        userEmailLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        userEmailLabel.setForeground(new java.awt.Color(136, 136, 128));
        userEmailLabel.setText("Email");
        userEmailLabel.setToolTipText("");

        javax.swing.GroupLayout userInfoPanelLayout = new javax.swing.GroupLayout(userInfoPanel);
        userInfoPanel.setLayout(userInfoPanelLayout);
        userInfoPanelLayout.setHorizontalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameLabel)
                    .addComponent(userEmailLabel))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        userInfoPanelLayout.setVerticalGroup(
            userInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(userEmailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout userCardLayout = new javax.swing.GroupLayout(userCard);
        userCard.setLayout(userCardLayout);
        userCardLayout.setHorizontalGroup(
            userCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(avatarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(userInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        userCardLayout.setVerticalGroup(
            userCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userCardLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(userCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avatarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        menuLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 11)); // NOI18N
        menuLabel.setText("    MENU");
        menuLabel.setPreferredSize(new java.awt.Dimension(188, 16));

        transactionsButton.setText("Transactions");
        transactionsButton.setBorder(null);
        transactionsButton.setFocusPainted(false);

        javax.swing.GroupLayout navigationPanelLayout = new javax.swing.GroupLayout(navigationPanel);
        navigationPanel.setLayout(navigationPanelLayout);
        navigationPanelLayout.setHorizontalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addGroup(navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bottomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(userCard, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(navigationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(menuLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(transactionsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        navigationPanelLayout.setVerticalGroup(
            navigationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navigationPanelLayout.createSequentialGroup()
                .addComponent(logoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transactionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 336, Short.MAX_VALUE)
                .addComponent(userCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bottomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        contentPanel.setPreferredSize(new java.awt.Dimension(820, 620));

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(navigationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(navigationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(contentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        logout();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void logoutButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseEntered
        applyLogoutStyle(true);
    }//GEN-LAST:event_logoutButtonMouseEntered

    private void logoutButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutButtonMouseExited
        applyLogoutStyle(false);
    }//GEN-LAST:event_logoutButtonMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avatarLabel;
    private javax.swing.JPanel avatarPanel;
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel logoLabel;
    private javax.swing.JPanel logoPanel;
    private javax.swing.JLabel logoSubLabel;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel menuLabel;
    private javax.swing.JPanel navigationPanel;
    private javax.swing.JButton transactionsButton;
    private javax.swing.JPanel userCard;
    private javax.swing.JLabel userEmailLabel;
    private javax.swing.JPanel userInfoPanel;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
