/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lorraine.views;

import com.formdev.flatlaf.FlatClientProperties;
import com.lorraine.main.MainFrame;
import com.lorraine.main.MainPanel;
import com.lorraine.main.Session;
import com.lorraine.models.LoginResult;
import com.lorraine.services.AuthenticationService;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author Lorraine G. Bulaclac, seany
 */
public class LoginPanel extends javax.swing.JPanel {

    private static final Logger LOGGER = Logger.getLogger(LoginPanel.class.getName());
    private final AuthenticationService authService = new AuthenticationService();
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
        initComponentProperties();
    }
    
    private void initComponentProperties() {
        loginCardPanel.putClientProperty(FlatClientProperties.STYLE, "arc:18;");
        
        String fieldStyle = "arc:10; borderWidth:1; focusWidth:0; innerFocusWidth:0;";
        emailField.putClientProperty(FlatClientProperties.STYLE, fieldStyle);
        emailField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "juandelacruz@email.com");

        passwordField.putClientProperty(FlatClientProperties.STYLE, fieldStyle);
        passwordField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Enter your password");
        signinButton.putClientProperty(FlatClientProperties.STYLE,
                "arc:10; borderWidth:0; focusWidth:0; innerFocusWidth:0;");
        
        errorLabel.setVisible(false);
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
        SwingUtilities.getRootPane(this).setDefaultButton(signinButton);
    }
    
    private void navigateToRegister() {
        AuthPanel auth = getAuthPanel();
        if (auth != null) auth.showRegister();
    }

    private AuthPanel getAuthPanel() {
        java.awt.Container parent = getParent();
        while (parent != null) {
            if (parent instanceof AuthPanel ap) return ap;
            parent = parent.getParent();
        }
        return null;
    }

    private void showError(String message) {
        errorLabel.setText(message);
        errorLabel.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        loginCardPanel = new javax.swing.JPanel();
        emailField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        registerRow = new javax.swing.JPanel();
        registerLink = new javax.swing.JLabel();
        registerLinkAction = new javax.swing.JButton();
        signinButton = new com.lorraine.swing.SpinnerButton();
        showHidePanel = new javax.swing.JPanel();
        showHideButton = new javax.swing.JToggleButton();
        passwordField = new javax.swing.JPasswordField();

        backgroundPanel.setBackground(new java.awt.Color(248, 248, 248));
        backgroundPanel.setOpaque(false);

        loginCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        loginCardPanel.setPreferredSize(new java.awt.Dimension(380, 385));

        emailField.setPreferredSize(new java.awt.Dimension(300, 38));

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(55, 65, 81));
        emailLabel.setText("EMAIL");

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(55, 65, 81));
        passwordLabel.setText("PASSWORD");

        titleLabel.setBackground(new java.awt.Color(17, 34, 39));
        titleLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        titleLabel.setText("Welcome Back");

        subtitleLabel.setBackground(new java.awt.Color(107, 114, 128));
        subtitleLabel.setText("Sign in to your account");

        errorLabel.setBackground(new java.awt.Color(255, 255, 255));
        errorLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(185, 28, 28));
        errorLabel.setPreferredSize(new java.awt.Dimension(300, 16));

        registerRow.setBackground(new java.awt.Color(255, 255, 255));
        registerRow.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        registerLink.setText("Don't have an account?");
        registerRow.add(registerLink);

        registerLinkAction.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        registerLinkAction.setForeground(new java.awt.Color(37, 99, 235));
        registerLinkAction.setText("Create one");
        registerLinkAction.setBorder(null);
        registerLinkAction.setContentAreaFilled(false);
        registerLinkAction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerLinkAction.addActionListener(this::registerLinkActionActionPerformed);
        registerRow.add(registerLinkAction);

        signinButton.setBackground(new java.awt.Color(17, 24, 39));
        signinButton.setForeground(new java.awt.Color(255, 255, 255));
        signinButton.setText("Sign In");
        signinButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        signinButton.setPreferredSize(new java.awt.Dimension(300, 38));
        signinButton.setSpinnerColor(java.awt.Color.white);
        signinButton.addActionListener(this::signinButtonActionPerformed);

        showHidePanel.setPreferredSize(new java.awt.Dimension(100, 38));
        showHidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showHideButton.setText("Show");
        showHideButton.setFocusPainted(false);
        showHideButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        showHideButton.setPreferredSize(new java.awt.Dimension(50, 38));
        showHideButton.addActionListener(this::showHideButtonActionPerformed);
        showHidePanel.add(showHideButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 0, 50, -1));

        passwordField.setPreferredSize(new java.awt.Dimension(300, 38));
        showHidePanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, -1));

        javax.swing.GroupLayout loginCardPanelLayout = new javax.swing.GroupLayout(loginCardPanel);
        loginCardPanel.setLayout(loginCardPanelLayout);
        loginCardPanelLayout.setHorizontalGroup(
            loginCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginCardPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(loginCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                    .addComponent(passwordLabel)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginCardPanelLayout.createSequentialGroup()
                        .addGroup(loginCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subtitleLabel)
                            .addComponent(titleLabel)
                            .addComponent(emailLabel))
                        .addGap(150, 150, 150))
                    .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(signinButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(showHidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        loginCardPanelLayout.setVerticalGroup(
            loginCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginCardPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitleLabel)
                .addGap(28, 28, 28)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showHidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(signinButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(registerRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(loginCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(loginCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(103, 103, 103))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerLinkActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerLinkActionActionPerformed
        navigateToRegister();
    }//GEN-LAST:event_registerLinkActionActionPerformed

    private void signinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signinButtonActionPerformed
        if (signinButton.isLoading()) return;

        String email    = emailField.getText().trim();
        String password = new String(passwordField.getPassword());

        if (email.isEmpty() || password.isEmpty()) {
            showError("Please fill in all fields.");
            return;
        }

        errorLabel.setVisible(false);
        signinButton.startLoading();

        new javax.swing.SwingWorker<LoginResult, Void>() {
            @Override
            protected LoginResult doInBackground() {
                return authService.loginUser(email, password);
            }

            @Override
            protected void done() {
                try {
                    LoginResult result = get();
                    if (!result.isSuccess()) {
                        showError(result.getMessage());
                        signinButton.stopLoading();
                    } else {
                        Session.login(result.getUser());
                        MainFrame mainFrame =
                            (MainFrame) SwingUtilities.getWindowAncestor(LoginPanel.this);
                        if (mainFrame != null) mainFrame.setView(new MainPanel());
                    }
                } catch (InterruptedException | ExecutionException e) {
                    LOGGER.log(Level.SEVERE, "Login error", e);
                    showError("Something went wrong. Please try again.");
                    signinButton.stopLoading();
                }
            }
        }.execute();
    }//GEN-LAST:event_signinButtonActionPerformed

    private void showHideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButtonActionPerformed
       if (showHideButton.isSelected()) {
           passwordField.setEchoChar((char) 0);
           showHideButton.setText("Hide");
       } else {
           passwordField.setEchoChar('*');
           showHideButton.setText("Show");
       }
    }//GEN-LAST:event_showHideButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JPanel loginCardPanel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JLabel registerLink;
    private javax.swing.JButton registerLinkAction;
    private javax.swing.JPanel registerRow;
    private javax.swing.JToggleButton showHideButton;
    private javax.swing.JPanel showHidePanel;
    private com.lorraine.swing.SpinnerButton signinButton;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
