/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.lorraine.views;

import com.formdev.flatlaf.FlatClientProperties;
import com.lorraine.main.MainFrame;
import com.lorraine.main.MainPanel;
import com.lorraine.main.Session;
import com.lorraine.models.AuthenticationResult;
import com.lorraine.models.LoginResult;
import com.lorraine.services.AuthenticationService;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author Lorraine G. Bulaclac, seany
 */
public class RegisterPanel extends javax.swing.JPanel {

    private static final Logger LOGGER = Logger.getLogger(RegisterPanel.class.getName());
    private final AuthenticationService authService = new AuthenticationService();
    /**
     * Creates new form LoginPanel
     */
    public RegisterPanel() {
        initComponents();
        initComponentProperties();
    }
    
    private void initComponentProperties() {
        registerCardPanel.putClientProperty(FlatClientProperties.STYLE, "arc:18;");

        String fieldStyle = "arc:10; borderWidth:1; focusWidth:0; innerFocusWidth:0;";
        firstNameField.putClientProperty(FlatClientProperties.STYLE, fieldStyle);
        firstNameField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Juan");

        lastNameField.putClientProperty(FlatClientProperties.STYLE, fieldStyle);
        lastNameField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Dela Cruz");

        emailField.putClientProperty(FlatClientProperties.STYLE, fieldStyle);
        emailField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "juandelacruz@email.com");

        passwordField.putClientProperty(FlatClientProperties.STYLE, fieldStyle);
        passwordField.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "At least 8 characters");

        errorLabel.setVisible(false);

        registerButton.putClientProperty(FlatClientProperties.STYLE,
                "arc:10; borderWidth:0; focusWidth:0; innerFocusWidth:0;");
    }
    
    @Override
    public void addNotify() {
        super.addNotify();
        
        SwingUtilities.getRootPane(this).setDefaultButton(registerButton);
    }
    
    private void navigateToLogin() {
        AuthPanel auth = getAuthPanel();
        if (auth != null) auth.showLogin();
    }

    private AuthPanel getAuthPanel() {
        java.awt.Container parent = getParent();
        while (parent != null) {
            if (parent instanceof AuthPanel ap) return ap;
            parent = parent.getParent();
        }
        return null;
    }

    private void showError(String message) {
        errorLabel.setText(message);
        errorLabel.setVisible(true);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        registerCardPanel = new javax.swing.JPanel();
        emailField = new javax.swing.JTextField();
        showHidePanel = new javax.swing.JPanel();
        showHideButton = new javax.swing.JToggleButton();
        passwordField = new javax.swing.JPasswordField();
        emailLabel = new javax.swing.JLabel();
        passwordLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        errorLabel = new javax.swing.JLabel();
        loginRow = new javax.swing.JPanel();
        loginLink = new javax.swing.JLabel();
        loginLinkAction = new javax.swing.JButton();
        registerButton = new com.lorraine.swing.SpinnerButton();
        firstNameLabel = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();

        backgroundPanel.setBackground(new java.awt.Color(248, 248, 248));
        backgroundPanel.setOpaque(false);

        registerCardPanel.setBackground(new java.awt.Color(255, 255, 255));
        registerCardPanel.setPreferredSize(new java.awt.Dimension(380, 428));

        emailField.setPreferredSize(new java.awt.Dimension(300, 38));

        showHidePanel.setPreferredSize(new java.awt.Dimension(100, 38));
        showHidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showHideButton.setText("Show");
        showHideButton.setFocusPainted(false);
        showHideButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        showHideButton.setPreferredSize(new java.awt.Dimension(50, 38));
        showHideButton.addActionListener(this::showHideButtonActionPerformed);
        showHidePanel.add(showHideButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 0, 50, -1));

        passwordField.setPreferredSize(new java.awt.Dimension(300, 38));
        showHidePanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        emailLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(55, 65, 81));
        emailLabel.setText("EMAIL");

        passwordLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        passwordLabel.setForeground(new java.awt.Color(55, 65, 81));
        passwordLabel.setText("PASSWORD");

        titleLabel.setBackground(new java.awt.Color(17, 34, 39));
        titleLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 22)); // NOI18N
        titleLabel.setText("Create an account");

        subtitleLabel.setBackground(new java.awt.Color(107, 114, 128));
        subtitleLabel.setText("Start tracking your finances today");

        errorLabel.setBackground(new java.awt.Color(255, 255, 255));
        errorLabel.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(185, 28, 28));
        errorLabel.setPreferredSize(new java.awt.Dimension(300, 16));

        loginRow.setBackground(new java.awt.Color(255, 255, 255));
        loginRow.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));

        loginLink.setText("Already have an account?");
        loginRow.add(loginLink);

        loginLinkAction.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        loginLinkAction.setForeground(new java.awt.Color(37, 99, 235));
        loginLinkAction.setText("Sign in");
        loginLinkAction.setBorder(null);
        loginLinkAction.setContentAreaFilled(false);
        loginLinkAction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginLinkAction.addActionListener(this::loginLinkActionActionPerformed);
        loginRow.add(loginLinkAction);

        registerButton.setBackground(new java.awt.Color(17, 24, 39));
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Create Account");
        registerButton.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        registerButton.setPreferredSize(new java.awt.Dimension(300, 38));
        registerButton.setSpinnerColor(java.awt.Color.white);
        registerButton.addActionListener(this::registerButtonActionPerformed);

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(55, 65, 81));
        firstNameLabel.setText("First Name");

        firstNameField.setPreferredSize(new java.awt.Dimension(144, 36));

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(55, 65, 81));
        lastNameLabel.setText("Last Name");

        lastNameField.setPreferredSize(new java.awt.Dimension(144, 36));

        javax.swing.GroupLayout registerCardPanelLayout = new javax.swing.GroupLayout(registerCardPanel);
        registerCardPanel.setLayout(registerCardPanelLayout);
        registerCardPanelLayout.setHorizontalGroup(
            registerCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerCardPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(registerCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailLabel)
                    .addComponent(passwordLabel)
                    .addComponent(loginRow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(registerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, registerCardPanelLayout.createSequentialGroup()
                        .addGroup(registerCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstNameLabel)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(registerCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lastNameLabel)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(errorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleLabel)
                    .addComponent(subtitleLabel)
                    .addComponent(showHidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        registerCardPanelLayout.setVerticalGroup(
            registerCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerCardPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitleLabel)
                .addGroup(registerCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(registerCardPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(registerCardPanelLayout.createSequentialGroup()
                        .addGroup(registerCardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20)
                .addComponent(emailLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showHidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(loginRow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout backgroundPanelLayout = new javax.swing.GroupLayout(backgroundPanel);
        backgroundPanel.setLayout(backgroundPanelLayout);
        backgroundPanelLayout.setHorizontalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(320, Short.MAX_VALUE)
                .addComponent(registerCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(320, Short.MAX_VALUE))
        );
        backgroundPanelLayout.setVerticalGroup(
            backgroundPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundPanelLayout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(registerCardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroundPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void loginLinkActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginLinkActionActionPerformed
        navigateToLogin();
    }//GEN-LAST:event_loginLinkActionActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        if (registerButton.isLoading()) return;

        String firstName = firstNameField.getText().trim();
        String lastName  = lastNameField.getText().trim();
        String email     = emailField.getText().trim();
        String password  = new String(passwordField.getPassword());

        if (firstName.isEmpty() || lastName.isEmpty() || email.isEmpty() || password.isEmpty()) {
            showError("Please fill in all fields.");
            return;
        }
        if (password.length() < 8) {
            showError("Password must be at least 8 characters.");
            return;
        }

        errorLabel.setVisible(false);
        registerButton.startLoading();

        new javax.swing.SwingWorker<AuthenticationResult, Void>() {
            @Override
            protected AuthenticationResult doInBackground() {
                return authService.registerUser(firstName, lastName, email, password);
            }

            @Override
            protected void done() {
                try {
                    AuthenticationResult result = get();
                    if (!result.isSuccess()) {
                        showError(result.getMessage());
                        registerButton.stopLoading();
                    } else {
                        // Auto-login after registration
                        LoginResult loginResult = authService.loginUser(email, password);
                        if (loginResult.isSuccess()) {
                            Session.login(loginResult.getUser());
                            MainFrame mainFrame =
                                (MainFrame) SwingUtilities.getWindowAncestor(RegisterPanel.this);
                            if (mainFrame != null) mainFrame.setView(new MainPanel());
                        } else {
                            navigateToLogin();
                        }
                    }
                } catch (InterruptedException | ExecutionException e) {
                    LOGGER.log(Level.SEVERE, "Registration error", e);
                    showError("Something went wrong. Please try again.");
                    registerButton.stopLoading();
                }
            }
        }.execute();
    }//GEN-LAST:event_registerButtonActionPerformed

    private void showHideButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showHideButtonActionPerformed
        if (showHideButton.isSelected()) {
           passwordField.setEchoChar((char) 0);
           showHideButton.setText("Hide");
       } else {
           passwordField.setEchoChar('*');
           showHideButton.setText("Show");
       }
    }//GEN-LAST:event_showHideButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel loginLink;
    private javax.swing.JButton loginLinkAction;
    private javax.swing.JPanel loginRow;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordLabel;
    private com.lorraine.swing.SpinnerButton registerButton;
    private javax.swing.JPanel registerCardPanel;
    private javax.swing.JToggleButton showHideButton;
    private javax.swing.JPanel showHidePanel;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
